/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteRouteImport } from './routes/user/route'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as ModeratorRouteRouteImport } from './routes/moderator/route'
import { Route as MessagesRouteRouteImport } from './routes/messages/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserpropertiesPropertiesRouteImport } from './routes/user/(properties)/properties'
import { Route as SearchmapMapRouteImport } from './routes/search/(map)/map'
import { Route as SearchlistListRouteImport } from './routes/search/(list)/list'
import { Route as PropertyaddAddRouteImport } from './routes/property/(add)/add'
import { Route as PropertypIdPIdRouteImport } from './routes/property/($pId)/$pId'
import { Route as OauthsuccessSuccessRouteImport } from './routes/oauth/(success)/success'
import { Route as ModeratorpropertyToApprovePropertyToApproveRouteImport } from './routes/moderator/(property-to-approve)/property-to-approve'
import { Route as MessagesPIdUserIdRouteImport } from './routes/messages/$pId.$userId'
import { Route as AuthemailVerifiedEmailVerifiedUnsuccessfullyRouteImport } from './routes/auth/(email-verified)/email-verified-unsuccessfully'
import { Route as AuthemailVerifiedEmailVerifiedSuccessfullyRouteImport } from './routes/auth/(email-verified)/email-verified-successfully'
import { Route as AdminuserManagementUserManagementRouteImport } from './routes/admin/(user-management)/user-management'

const UserRouteRoute = UserRouteRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/settings/route.lazy').then((d) => d.Route),
)
const ModeratorRouteRoute = ModeratorRouteRouteImport.update({
  id: '/moderator',
  path: '/moderator',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRouteRoute = MessagesRouteRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/messages/route.lazy').then((d) => d.Route),
)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserpropertiesPropertiesRoute =
  UserpropertiesPropertiesRouteImport.update({
    id: '/(properties)/properties',
    path: '/properties',
    getParentRoute: () => UserRouteRoute,
  } as any).lazy(() =>
    import('./routes/user/(properties)/properties.lazy').then((d) => d.Route),
  )
const SearchmapMapRoute = SearchmapMapRouteImport.update({
  id: '/search/(map)/map',
  path: '/search/map',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/search/(map)/map.lazy').then((d) => d.Route),
)
const SearchlistListRoute = SearchlistListRouteImport.update({
  id: '/search/(list)/list',
  path: '/search/list',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/search/(list)/list.lazy').then((d) => d.Route),
)
const PropertyaddAddRoute = PropertyaddAddRouteImport.update({
  id: '/property/(add)/add',
  path: '/property/add',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/property/(add)/add.lazy').then((d) => d.Route),
)
const PropertypIdPIdRoute = PropertypIdPIdRouteImport.update({
  id: '/property/($pId)/$pId',
  path: '/property/$pId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/property/($pId)/$pId.lazy').then((d) => d.Route),
)
const OauthsuccessSuccessRoute = OauthsuccessSuccessRouteImport.update({
  id: '/oauth/(success)/success',
  path: '/oauth/success',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/oauth/(success)/success.lazy').then((d) => d.Route),
)
const ModeratorpropertyToApprovePropertyToApproveRoute =
  ModeratorpropertyToApprovePropertyToApproveRouteImport.update({
    id: '/(property-to-approve)/property-to-approve',
    path: '/property-to-approve',
    getParentRoute: () => ModeratorRouteRoute,
  } as any).lazy(() =>
    import('./routes/moderator/(property-to-approve)/property-to-approve.lazy').then(
      (d) => d.Route,
    ),
  )
const MessagesPIdUserIdRoute = MessagesPIdUserIdRouteImport.update({
  id: '/$pId/$userId',
  path: '/$pId/$userId',
  getParentRoute: () => MessagesRouteRoute,
} as any).lazy(() =>
  import('./routes/messages/$pId.$userId.lazy').then((d) => d.Route),
)
const AuthemailVerifiedEmailVerifiedUnsuccessfullyRoute =
  AuthemailVerifiedEmailVerifiedUnsuccessfullyRouteImport.update({
    id: '/auth/(email-verified)/email-verified-unsuccessfully',
    path: '/auth/email-verified-unsuccessfully',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/auth/(email-verified)/email-verified-unsuccessfully.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthemailVerifiedEmailVerifiedSuccessfullyRoute =
  AuthemailVerifiedEmailVerifiedSuccessfullyRouteImport.update({
    id: '/auth/(email-verified)/email-verified-successfully',
    path: '/auth/email-verified-successfully',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/auth/(email-verified)/email-verified-successfully.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminuserManagementUserManagementRoute =
  AdminuserManagementUserManagementRouteImport.update({
    id: '/(user-management)/user-management',
    path: '/user-management',
    getParentRoute: () => AdminRouteRoute,
  } as any).lazy(() =>
    import('./routes/admin/(user-management)/user-management.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/messages': typeof MessagesRouteRouteWithChildren
  '/moderator': typeof ModeratorRouteRouteWithChildren
  '/settings': typeof SettingsRouteRoute
  '/user': typeof UserRouteRouteWithChildren
  '/admin/user-management': typeof AdminuserManagementUserManagementRoute
  '/auth/email-verified-successfully': typeof AuthemailVerifiedEmailVerifiedSuccessfullyRoute
  '/auth/email-verified-unsuccessfully': typeof AuthemailVerifiedEmailVerifiedUnsuccessfullyRoute
  '/messages/$pId/$userId': typeof MessagesPIdUserIdRoute
  '/moderator/property-to-approve': typeof ModeratorpropertyToApprovePropertyToApproveRoute
  '/oauth/success': typeof OauthsuccessSuccessRoute
  '/property/$pId': typeof PropertypIdPIdRoute
  '/property/add': typeof PropertyaddAddRoute
  '/search/list': typeof SearchlistListRoute
  '/search/map': typeof SearchmapMapRoute
  '/user/properties': typeof UserpropertiesPropertiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/messages': typeof MessagesRouteRouteWithChildren
  '/moderator': typeof ModeratorRouteRouteWithChildren
  '/settings': typeof SettingsRouteRoute
  '/user': typeof UserRouteRouteWithChildren
  '/admin/user-management': typeof AdminuserManagementUserManagementRoute
  '/auth/email-verified-successfully': typeof AuthemailVerifiedEmailVerifiedSuccessfullyRoute
  '/auth/email-verified-unsuccessfully': typeof AuthemailVerifiedEmailVerifiedUnsuccessfullyRoute
  '/messages/$pId/$userId': typeof MessagesPIdUserIdRoute
  '/moderator/property-to-approve': typeof ModeratorpropertyToApprovePropertyToApproveRoute
  '/oauth/success': typeof OauthsuccessSuccessRoute
  '/property/$pId': typeof PropertypIdPIdRoute
  '/property/add': typeof PropertyaddAddRoute
  '/search/list': typeof SearchlistListRoute
  '/search/map': typeof SearchmapMapRoute
  '/user/properties': typeof UserpropertiesPropertiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/messages': typeof MessagesRouteRouteWithChildren
  '/moderator': typeof ModeratorRouteRouteWithChildren
  '/settings': typeof SettingsRouteRoute
  '/user': typeof UserRouteRouteWithChildren
  '/admin/(user-management)/user-management': typeof AdminuserManagementUserManagementRoute
  '/auth/(email-verified)/email-verified-successfully': typeof AuthemailVerifiedEmailVerifiedSuccessfullyRoute
  '/auth/(email-verified)/email-verified-unsuccessfully': typeof AuthemailVerifiedEmailVerifiedUnsuccessfullyRoute
  '/messages/$pId/$userId': typeof MessagesPIdUserIdRoute
  '/moderator/(property-to-approve)/property-to-approve': typeof ModeratorpropertyToApprovePropertyToApproveRoute
  '/oauth/(success)/success': typeof OauthsuccessSuccessRoute
  '/property/($pId)/$pId': typeof PropertypIdPIdRoute
  '/property/(add)/add': typeof PropertyaddAddRoute
  '/search/(list)/list': typeof SearchlistListRoute
  '/search/(map)/map': typeof SearchmapMapRoute
  '/user/(properties)/properties': typeof UserpropertiesPropertiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/messages'
    | '/moderator'
    | '/settings'
    | '/user'
    | '/admin/user-management'
    | '/auth/email-verified-successfully'
    | '/auth/email-verified-unsuccessfully'
    | '/messages/$pId/$userId'
    | '/moderator/property-to-approve'
    | '/oauth/success'
    | '/property/$pId'
    | '/property/add'
    | '/search/list'
    | '/search/map'
    | '/user/properties'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/messages'
    | '/moderator'
    | '/settings'
    | '/user'
    | '/admin/user-management'
    | '/auth/email-verified-successfully'
    | '/auth/email-verified-unsuccessfully'
    | '/messages/$pId/$userId'
    | '/moderator/property-to-approve'
    | '/oauth/success'
    | '/property/$pId'
    | '/property/add'
    | '/search/list'
    | '/search/map'
    | '/user/properties'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/messages'
    | '/moderator'
    | '/settings'
    | '/user'
    | '/admin/(user-management)/user-management'
    | '/auth/(email-verified)/email-verified-successfully'
    | '/auth/(email-verified)/email-verified-unsuccessfully'
    | '/messages/$pId/$userId'
    | '/moderator/(property-to-approve)/property-to-approve'
    | '/oauth/(success)/success'
    | '/property/($pId)/$pId'
    | '/property/(add)/add'
    | '/search/(list)/list'
    | '/search/(map)/map'
    | '/user/(properties)/properties'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  MessagesRouteRoute: typeof MessagesRouteRouteWithChildren
  ModeratorRouteRoute: typeof ModeratorRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRoute
  UserRouteRoute: typeof UserRouteRouteWithChildren
  AuthemailVerifiedEmailVerifiedSuccessfullyRoute: typeof AuthemailVerifiedEmailVerifiedSuccessfullyRoute
  AuthemailVerifiedEmailVerifiedUnsuccessfullyRoute: typeof AuthemailVerifiedEmailVerifiedUnsuccessfullyRoute
  OauthsuccessSuccessRoute: typeof OauthsuccessSuccessRoute
  PropertypIdPIdRoute: typeof PropertypIdPIdRoute
  PropertyaddAddRoute: typeof PropertyaddAddRoute
  SearchlistListRoute: typeof SearchlistListRoute
  SearchmapMapRoute: typeof SearchmapMapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderator': {
      id: '/moderator'
      path: '/moderator'
      fullPath: '/moderator'
      preLoaderRoute: typeof ModeratorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/(properties)/properties': {
      id: '/user/(properties)/properties'
      path: '/properties'
      fullPath: '/user/properties'
      preLoaderRoute: typeof UserpropertiesPropertiesRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/search/(map)/map': {
      id: '/search/(map)/map'
      path: '/search/map'
      fullPath: '/search/map'
      preLoaderRoute: typeof SearchmapMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/(list)/list': {
      id: '/search/(list)/list'
      path: '/search/list'
      fullPath: '/search/list'
      preLoaderRoute: typeof SearchlistListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/(add)/add': {
      id: '/property/(add)/add'
      path: '/property/add'
      fullPath: '/property/add'
      preLoaderRoute: typeof PropertyaddAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/($pId)/$pId': {
      id: '/property/($pId)/$pId'
      path: '/property/$pId'
      fullPath: '/property/$pId'
      preLoaderRoute: typeof PropertypIdPIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/(success)/success': {
      id: '/oauth/(success)/success'
      path: '/oauth/success'
      fullPath: '/oauth/success'
      preLoaderRoute: typeof OauthsuccessSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderator/(property-to-approve)/property-to-approve': {
      id: '/moderator/(property-to-approve)/property-to-approve'
      path: '/property-to-approve'
      fullPath: '/moderator/property-to-approve'
      preLoaderRoute: typeof ModeratorpropertyToApprovePropertyToApproveRouteImport
      parentRoute: typeof ModeratorRouteRoute
    }
    '/messages/$pId/$userId': {
      id: '/messages/$pId/$userId'
      path: '/$pId/$userId'
      fullPath: '/messages/$pId/$userId'
      preLoaderRoute: typeof MessagesPIdUserIdRouteImport
      parentRoute: typeof MessagesRouteRoute
    }
    '/auth/(email-verified)/email-verified-unsuccessfully': {
      id: '/auth/(email-verified)/email-verified-unsuccessfully'
      path: '/auth/email-verified-unsuccessfully'
      fullPath: '/auth/email-verified-unsuccessfully'
      preLoaderRoute: typeof AuthemailVerifiedEmailVerifiedUnsuccessfullyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/(email-verified)/email-verified-successfully': {
      id: '/auth/(email-verified)/email-verified-successfully'
      path: '/auth/email-verified-successfully'
      fullPath: '/auth/email-verified-successfully'
      preLoaderRoute: typeof AuthemailVerifiedEmailVerifiedSuccessfullyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/(user-management)/user-management': {
      id: '/admin/(user-management)/user-management'
      path: '/user-management'
      fullPath: '/admin/user-management'
      preLoaderRoute: typeof AdminuserManagementUserManagementRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminuserManagementUserManagementRoute: typeof AdminuserManagementUserManagementRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminuserManagementUserManagementRoute:
    AdminuserManagementUserManagementRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface MessagesRouteRouteChildren {
  MessagesPIdUserIdRoute: typeof MessagesPIdUserIdRoute
}

const MessagesRouteRouteChildren: MessagesRouteRouteChildren = {
  MessagesPIdUserIdRoute: MessagesPIdUserIdRoute,
}

const MessagesRouteRouteWithChildren = MessagesRouteRoute._addFileChildren(
  MessagesRouteRouteChildren,
)

interface ModeratorRouteRouteChildren {
  ModeratorpropertyToApprovePropertyToApproveRoute: typeof ModeratorpropertyToApprovePropertyToApproveRoute
}

const ModeratorRouteRouteChildren: ModeratorRouteRouteChildren = {
  ModeratorpropertyToApprovePropertyToApproveRoute:
    ModeratorpropertyToApprovePropertyToApproveRoute,
}

const ModeratorRouteRouteWithChildren = ModeratorRouteRoute._addFileChildren(
  ModeratorRouteRouteChildren,
)

interface UserRouteRouteChildren {
  UserpropertiesPropertiesRoute: typeof UserpropertiesPropertiesRoute
}

const UserRouteRouteChildren: UserRouteRouteChildren = {
  UserpropertiesPropertiesRoute: UserpropertiesPropertiesRoute,
}

const UserRouteRouteWithChildren = UserRouteRoute._addFileChildren(
  UserRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  MessagesRouteRoute: MessagesRouteRouteWithChildren,
  ModeratorRouteRoute: ModeratorRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRoute,
  UserRouteRoute: UserRouteRouteWithChildren,
  AuthemailVerifiedEmailVerifiedSuccessfullyRoute:
    AuthemailVerifiedEmailVerifiedSuccessfullyRoute,
  AuthemailVerifiedEmailVerifiedUnsuccessfullyRoute:
    AuthemailVerifiedEmailVerifiedUnsuccessfullyRoute,
  OauthsuccessSuccessRoute: OauthsuccessSuccessRoute,
  PropertypIdPIdRoute: PropertypIdPIdRoute,
  PropertyaddAddRoute: PropertyaddAddRoute,
  SearchlistListRoute: SearchlistListRoute,
  SearchmapMapRoute: SearchmapMapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
